### ISSUE TITLE
[Feature] - UI 손보기

### ISSUE THREAD

**Issue by shimseohyun** [irumi-dgu/irumi-client#16]
## 🛠 Issue

UI 구석구석 손보는 작업

## 📝 To-do

- [x] lanternCard 400px 기준으로 재작업
- [x] lanternCard 에 like btn 추가하기

- [x] searchBar에 아이콘 추가
- [x] searchBar 색깔 고민해보기
- [x] NightTime Theme gradient 고민해보기
