### ISSUE TITLE
[FixBug] - 충돌관련 이슈들 해결

### ISSUE THREAD

**Issue by shimseohyun** [irumi-dgu/irumi-client#23]
## 🛠 Issue
충돌관련 이슈들을 해결합니다.

## 📝 To-do

- [x] 라우터 오류 해결
- [x] Page 관련 컴포넌트 이름 변경
- [x] 램프부분 합의 후 변경 필요
- [x] 렌턴 카드 이미지 경로 수정
