### ISSUE TITLE
[QA] - 포츈쿠키

### ISSUE THREAD

**Issue by shimseohyun** [irumi-dgu/irumi-client#39]
## 🛠 Issue
포츈 쿠키 QA 후 수정사항입니다.

## 📝 To-do

`FixView` 사용해주세요! mainPage 컴포넌트 참고
- [x] 화면 스크롤 안 되게 하기

- [x] 행운의 연꽃잎 클릭시 연꽃이 올라감... 이미지 부자연스러움
![IMG_6282](https://github.com/irumi-dgu/irumi-client/assets/117021241/bf32283d-337a-4b6e-a948-b5e74abbe893)

- [x] 이미지 저장 안되는 듯?
- [x] 낮 배경일때 동그라미 버튼 글자가 안보여요 ㅜ 테마 처리해야할듯
![IMG_6284](https://github.com/irumi-dgu/irumi-client/assets/117021241/58c5df70-ed40-4fea-9c04-3c821dc2e084)

- [x] 내용이 이렇게 중앙에 박히는게 맞나요?
![IMG_6285](https://github.com/irumi-dgu/irumi-client/assets/117021241/04a25777-819b-441e-ab7c-4ae6b219b0ea)
