### ISSUE TITLE
[QA] - 소원 작성

### ISSUE THREAD

**Issue by shimseohyun** [irumi-dgu/irumi-client#40]
## 🛠 Issue
소원 작성 QA 후 수정사항입니다.

## 📝 To-do

`FixView` 사용해주세요! mainPage 컴포넌트 참고
- [x] 연등 컬러 선택 버튼 주소창에 안 잘리게
- [x] 소원 작성하기 버튼 주소창에 안 잘리게

- [x] 소원 작성하기 닉네임 input 패딩 값 조절하기
- [x] input 클릭시 화면 확대 막기
