### ISSUE TITLE
[QA] - 소원 둘러보기

### ISSUE THREAD

**Issue by shimseohyun** [irumi-dgu/irumi-client#41]
## 🛠 Issue
소원 둘러보기 QA 피드백 사항입니다.

## 📝 To-do

- [x] 최상단으로 올렸을때 서치 바 고정 시키기
- [x] 서치바 클릭시 화면 확대되는것 고치기
- [x] 서치 버튼 클릭시 서치되게하기
