### ISSUE TITLE
[QA] - 소원 디테일

### ISSUE THREAD

**Issue by shimseohyun** [irumi-dgu/irumi-client#42]
## 🛠 Issue

소원 디테일 QA 후 수정사항입니다.

## 📝 To-do

- [x] 좋아요버튼 중복 적용 해결
- [x] 주소창때문에 하단 안 가리게 FixView로 바꿔주세요
- [ ] 이상하게 버튼들이 잘 안 눌리는 듯...? 점도 그렇고 신고버튼들도 그렇구...
- [ ] 신고, 삭제 모달띄웠을때 닫기 말고 배경 눌러도 닫혔으면 좋겠습니다.
- [ ] 다른 모달도 동일
- [ ] 백버튼 뺄까요? 강민오빠가 말했던 봤던 위치로 되돌아가기가 안된다
