### ISSUE TITLE
[QA] - 등불쓰기

### ISSUE THREAD

**Issue by shimseohyun** [irumi-dgu/irumi-client#43]
## 🛠 Issue

등불쓰기에 대한 QA입니다

## 📝 To-do

- [x] Fix view로 바꿔주세요.
- [x] 연등달기 모션 이상해서 수정필요
- [x] 연등 달리면 메인으로 돌아가야할듯
