### ISSUE TITLE
[QA] - 최종 마무리

### ISSUE THREAD

**Issue by shimseohyun** [irumi-dgu/irumi-client#64]
## 🛠 Issue
배포전 마지막 QA 수정사항입니다.

## 📝 To-do
- [x] LampFlyPage line, text 깨짐
- [x] LampFlyPage 모션에 Scale down 적용
- [x] 검색바 테마마다 바꾸기
- [x] mainPage 등불 버튼 수정
